[package]
name = "cubemoma"
version = "0.0.6"
edition = "2024"
license = "BSD-2-Clause"
description = "A multi-word modular arithmetic library based on CubeCL"
repository = "https://github.com/newsniper-org/cubemoma"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
getrandom = { version = "0.3.4", features = ["std"] }
rand = { version = "0.9.2", features = ["simd_support", "unbiased"]}
wasm-bindgen = { version = "0.2.105", features = ["std"] }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"]}

[[bench]]
name = "cpu_fp_ops"
harness = false

[features]
default = ["cpu"]
cpu = []
gpu = []

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.3.4", features = ["std", "wasm_js"] }
serde = { version = "1.0.228", features = ["std", "serde_derive", "derive"]}
serde_json = { version = "1.0.145", features = ["std", "preserve_order"]}
wasm-bindgen = { version = "0.2.105", features = ["std", "serde", "serde-serialize", "serde_json"] }

[profile.bench]
debug = false
opt-level = 3
lto = true

[profile.release]
debug = false
opt-level = 3
lto = true
